<a href="https://colab.research.google.com/github/nurayyubov/GitHub-repos/blob/main/Copy_of_mohirdev_NumPy_amaliy_vazifa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np
np.version
np.show_config

<function numpy.__config__.show(mode='stdout')>



```
# This is formatted as code
```

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
numlist = [6,7,3,1,9,0]
arr = np.array(numlist)
arr

array([6, 7, 3, 1, 9, 0])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr4 = np.arange(0,100,5)
arr4.nbytes

160

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr6 = np.zeros(12)
arr6[5]=1
arr6

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.

1.   List item
2.   List item





`💡Ishora` arange

In [ ]:
vektor = np.arange(20,60)
vektor

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
teskari_vektor = -np.sort(-vektor)
teskari_vektor

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr9 = np.arange(12,21)
narr9 = np.reshape(arr9, newshape=(3,3))
narr9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
arr10 = np.nonzero([3, 7, 0, 0, 9, 0])
arr10


(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr11 = np.random.random((2, 2, 2))
arr11


array([[[0.93600338, 0.29709397],
        [0.88015968, 0.9176676 ]],

       [[0.80090768, 0.8155303 ],
        [0.24892384, 0.52431845]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr12 = np.random.random((9,9))
print('min: ', np.min(arr12))
print('max: ', np.max(arr12))

min:  0.011689455842546548
max:  0.9828981622720765


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
Nan
False
False
Nan
True
True


NameError: name 'Nan' is not defined



```
# This is formatted as code
```

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr1463 = np.random.random((6,3))
arr1434 = np.random.random((3,4))
arrkopaytma = np.dot(arr1463, arr1434)
print("6x3 matritsa: \n",arr1463)
print("\n3x4 matritsa: \n", arr1434)
print("\nularning ko'paytmasi: \n",arrkopaytma)




6x3 matritsa: 
 [[0.68788709 0.50423622 0.53180999]
 [0.2889049  0.92063387 0.1001568 ]
 [0.99999908 0.61843473 0.01337203]
 [0.58323925 0.29728116 0.72649309]
 [0.29542481 0.5003023  0.72104369]
 [0.59918704 0.56306479 0.13625672]]

3x4 matritsa: 
 [[0.52397973 0.59234314 0.51464594 0.35105277]
 [0.84310812 0.48628013 0.33953911 0.52290427]
 [0.13700301 0.24506432 0.88169435 0.18987158]]

ularning ko'paytmasi: 
 [[0.8584241  0.7829929  0.99412007 0.60612754]
 [0.94129598 0.64336165 0.54958262 0.60184117]
 [1.04721859 0.89635212 0.73641828 0.67697357]
 [0.65577744 0.66807723 1.04164514 0.49813773]
 [0.6753907  0.59498201 0.95765153 0.50222561]
 [0.80735394 0.66212322 0.61968848 0.53064653]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
10
10

10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1,2])
b = np.array([4,5])
print("a>b", a>b)
print("a >= b", a>=b)
print("a<b",a<b)
print("a <= b", a <= b)

a>b [False False]
a >= b [False False]
a<b [ True  True]
a <= b [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
<ipython-input-23-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-23-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-23-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)
array([-9.22337204e+18])

<ipython-input-23-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-23-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-23-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
n = np.arange(0,30,2)
print("birinchi massiv: ",n)
m = np.arange(0,30,3)
print("ikkinchi massiv: ",m)
print("umumiy qiymatlar: ", np.intersect1d(n,m))

birinchi massiv:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
ikkinchi massiv:  [ 0  3  6  9 12 15 18 21 24 27]
umumiy qiymatlar:  [ 0  6 12 18 24]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni

*   List item
*   List item

quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.



```
# This is formatted as code
```

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
arr19 = np.random.randint(-10,10,10)
print("massiv: ", arr19)

arr19_modulus = arr19[arr19 > 0] % 10
print("\nModulus (%) usuli natijasi :")
print(arr19_modulus)

arr19_floor = np.floor(arr19[arr19 > 0])
print("\nnp.floor usuli natijasi:")
print(arr19_floor)

arr19_astype = arr19[arr19 > 0].astype(int)
print("\nastype(int) usuli natijasi:")
print(arr19_astype)

arr19_trunc = np.trunc(arr19[arr19 > 0])
print("\nnp.trunc usuli natijasi:")
print(arr19_trunc)

massiv:  [-5 -8 -2 -9  3 -8  5 -6  4 -9]

Modulus (%) usuli natijasi :
[3 5 4]

np.floor usuli natijasi:
[3. 5. 4.]

astype(int) usuli natijasi:
[3 5 4]

np.trunc usuli natijasi:
[3. 5. 4.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.

> Add blockquote





`💡Ishora` np.arange

In [ ]:
arr20 = np.random.randint(0,3,9)
arr20.reshape(3,3)

array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 0]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [6]:
arr21 = np.random.randn(10)
sortarr = sorted(arr21)
sortarr

[-1.3284853277756759,
 -0.6819857711531249,
 -0.652790745156188,
 -0.605776179194354,
 -0.5372326587939328,
 -0.29858215825403106,
 -0.26662120220675334,
 -0.22923532198940433,
 0.2753465117518914,
 0.33516530850750276]

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [17]:
aarr = np.random.random(5)
barr = np.random.random(5)
natija = np.array_equal(aarr, barr)
natija

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [18]:
arr1463 = np.random.random((6,3))
arr1434 = np.random.random((3,4))
arrkopaytma = np.dot(arr1463, arr1434)
print("6x3 matritsa: \n",arr1463)
print("\n3x4 matritsa: \n", arr1434)
print("\nularning ko'paytmasi: \n",arrkopaytma)

6x3 matritsa: 
 [[0.23098735 0.03294181 0.02266555]
 [0.42289999 0.14862383 0.14625274]
 [0.26849929 0.58303079 0.44643149]
 [0.70614388 0.04496858 0.6866456 ]
 [0.32349409 0.27636599 0.73562784]
 [0.44823776 0.83727543 0.28681753]]

3x4 matritsa: 
 [[0.0707431  0.00861483 0.94998901 0.0303405 ]
 [0.09867853 0.62636677 0.50481476 0.11991857]
 [0.99298798 0.58016686 0.04439744 0.79635756]]

ularning ko'paytmasi: 
 [[0.04209803 0.03577337 0.23707124 0.02900849]
 [0.18981045 0.18158723 0.4832711  0.14712323]
 [0.51982819 0.62650894 0.56921434 0.43358171]
 [0.73622307 0.43261916 0.72401504 0.57363274]
 [0.78062596 0.60268021 0.47948946 0.62877917]
 [0.3991372  0.69470503 0.86122391 0.34241394]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [26]:
import numpy as np

arr24 = np.random.random(5)
print("1-array: ", arr24)

arr24[np.argmax(arr24)] = 0
print("2-array: ", arr24)


1-array:  [0.03451511 0.76397739 0.85786529 0.85652204 0.97149783]
2-array:  [0.03451511 0.76397739 0.85786529 0.85652204 0.        ]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [32]:
bugun = np.datetime64('today')
kecha = bugun - np.timedelta64(1,'D')
erta =  bugun + np.timedelta64(1,'D')
print("kecha: ", kecha)
print("bugun: ", bugun)
print("erta : ", erta)

kecha:  2024-12-22
bugun:  2024-12-23
erta :  2024-12-24


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


[link text](https://)`💡Ishora` np.arange(dtype=datetime64['D'])

In [35]:
yanvar16 = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')
print('2016-yil Yanvar oyi sanalari:\n', yanvar16)


2016-yil Yanvar oyi sanalari:
 ['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.



`💡Ishora` %, np.floor, astype, np.trunc`

In [37]:
arr19 = np.random.randint(0,20,10)
print("massiv: ", arr19)

arr19_modulus = arr19[arr19 > 0] % 1
print("\nModulus (%) usuli natijasi :")
print(arr19_modulus)

arr19_floor = np.floor(arr19[arr19 > 0])
print("\nnp.floor usuli natijasi:")
print(arr19_floor)

arr19_astype = arr19[arr19 > 0].astype(int)
print("\nastype(int) usuli natijasi:")
print(arr19_astype)

arr19_trunc = np.trunc(arr19[arr19 > 0])
print("\nnp.trunc usuli natijasi:")
print(arr19_trunc)

massiv:  [ 9 11  0  8 15  2 15 15  8 10]

Modulus (%) usuli natijasi :
[0 0 0 0 0 0 0 0 0]

np.floor usuli natijasi:
[ 9. 11.  8. 15.  2. 15. 15.  8. 10.]

astype(int) usuli natijasi:
[ 9 11  8 15  2 15 15  8 10]

np.trunc usuli natijasi:
[ 9. 11.  8. 15.  2. 15. 15.  8. 10.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [47]:
mas1 = np.random.randint(0,10,5)
yigindi = np.add.reduce(mas1)
print("massiv: ", mas1)
print("yig'indi: ", yigindi)

massiv:  [9 5 9 2 8]
yig'indi:  33


29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.

> Add blockquote




`💡Ishora` array[::4]

In [48]:
import numpy as np

vektor = np.array([1, 2, 3, 4, 5])
print("Asl vektor:", vektor)

nollar_soni = 3
uzunlik = len(vektor) + (len(vektor) - 1) * nollar_soni
yangi_vektor = np.zeros(uzunlik, dtype=int)
yangi_vektor[::nollar_soni + 1] = vektor

print("Yangi vektor:", yangi_vektor)

Asl vektor: [1 2 3 4 5]
Yangi vektor: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [50]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
stride_size = a.strides[0]
b = as_strided(a, shape=(len(a) - 3, 4), strides=(stride_size, stride_size))

print("Yaratilgan b massiv:")
print(b)

Yaratilgan b massiv:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash

*   List item
*   List item

qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [53]:
massiv = np.random.randint(1, 20, size=10)
print("Asl massiv:", massiv)
qiymatlar, takrorlanishlar = np.unique(massiv, return_counts=True)
print("\nHar bir qiymat va uning takrorlanish soni:")
for q, t in zip(qiymatlar, takrorlanishlar):
    print(f"Qiymat: {q}, Takrorlanish: {t}")

eng_kop_takrorlangan = qiymatlar[np.argmax(takrorlanishlar)]
print("\nEng ko'p takrorlangan qiymat:", eng_kop_takrorlangan)


Asl massiv: [10 12 19  2  4  9  2  7 10  9]

Har bir qiymat va uning takrorlanish soni:
Qiymat: 2, Takrorlanish: 2
Qiymat: 4, Takrorlanish: 1
Qiymat: 7, Takrorlanish: 1
Qiymat: 9, Takrorlanish: 2
Qiymat: 10, Takrorlanish: 2
Qiymat: 12, Takrorlanish: 1
Qiymat: 19, Takrorlanish: 1

Eng ko'p takrorlangan qiymat: 2


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

savol: yoshingiz nechida?
javob: 20